"""
Pydantic models for promise-source matching.

This module is the SINGLE SOURCE OF TRUTH for:
1. Match table schema (via field names and types)
2. Validation rules (via Pydantic validators)
3. Documentation (via Field descriptions)

Matches promises against source documents (motions/propositions) which contain
substantive policy content, rather than procedural vote text.
"""

from datetime import datetime

from pydantic import BaseModel, Field


class PromiseVoteMatch(BaseModel):
    """
    A match between a promise and a source document based on semantic similarity.

    Matches are generated by computing cosine similarity between
    promise embeddings and source embeddings (motions/propositions).
    """

    match_id: str = Field(description="Unique match identifier (UUID)")
    promise_id: str = Field(description="FK to promise_embeddings.promise_id")
    source_dok_id: str = Field(description="FK to source_embeddings.dok_id (motion or proposition)")
    similarity_score: float = Field(
        description="Cosine similarity score (0-1, higher = more similar)",
        ge=0.0,
        le=1.0,
    )
    matched_at: datetime = Field(description="Timestamp when match was computed")


def get_match_columns() -> list[tuple[str, str]]:
    """Generate SQL column definitions from PromiseVoteMatch Pydantic model."""
    columns = []
    for field_name, field_info in PromiseVoteMatch.model_fields.items():
        annotation = field_info.annotation
        is_required = field_info.is_required()

        if annotation is str:
            sql_type = "VARCHAR" + (" NOT NULL" if is_required else "")
        elif annotation is datetime:
            sql_type = "TIMESTAMP" + (" NOT NULL" if is_required else "")
        elif annotation is float:
            sql_type = "DOUBLE" + (" NOT NULL" if is_required else "")
        else:
            sql_type = "VARCHAR" + (" NOT NULL" if is_required else "")

        columns.append((field_name, sql_type))
    return columns
