-- Staging model for dokumentlista (documents)
-- Source abstraction layer with deduplication
-- dok_id is the natural key - keep most recent record per dok_id

select
    traff,
    "domain",
    "database",
    datum,
    id,
    slutdatum,
    plats,
    klockslag,
    publicerad,
    systemdatum,
    undertitel,
    kalla,
    kall_id,
    dok_id,
    dokumentformat,
    dokument_url_text,
    dokument_url_html,
    dokumentstatus_url_xml,
    inlamnad,
    motionstid,
    tilldelat,
    lang,
    url,
    relurl,
    titel,
    rm,
    organ,
    relaterat_id,
    doktyp,
    typ,
    subtyp,
    beteckning,
    tempbeteckning,
    nummer,
    status,
    score,
    sokdata__titel,
    sokdata__undertitel,
    sokdata__soktyp,
    sokdata__statusrad,
    sokdata__brodsmula,
    sokdata__parti_kod,
    sokdata__parti_namn,
    sokdata__parti_website_url,
    sokdata__parti_website_namn,
    sokdata__parti_epost,
    sokdata__parti_telefon,
    sokdata__parti_telefontider,
    sokdata__parti_logotyp_img_id,
    sokdata__parti_logotyp_img_url,
    sokdata__parti_logotyp_img_alt,
    sokdata__parti_mandat,
    sokdata__kalenderprio,
    summary,
    notisrubrik,
    notis,
    avdelning,
    avdelningar__avdelning,
    struktur,
    audio,
    video,
    debattgrupp,
    debattdag,
    beslutsdag,
    beredningsdag,
    justeringsdag,
    beslutad,
    debattsekunder,
    ardometyp,
    reservationer,
    debattnamn,
    dokumentnamn,
    _dlt_load_id,
    _dlt_id,
    filbilaga__fil,
    debatt__anforande,
    dokintressent__intressent,
    cmskategorier__cmskategori,
    cmsetiketter__cmsetikett,
    cmstyp,
    linklista__link,
    img_url,
    img_text,
    img_title,
    img_large,
    img_id,
    cms_rubrikniva,
    img_fotograf,
    img_tumnagel_url,
    notisslutdatum,
    egenskaper__egenskap,
    slutdatum__v_text,
    publicerad__v_text,
    dokreferens__referens
from {{ source('raw_riksdagen', 'dokumentlista') }}
where dok_id is not null
qualify row_number() over (
    partition by dok_id 
    order by systemdatum desc nulls last
) = 1
