-- Staging model for dokumentstatus (detailed document status)
-- Source abstraction layer with deduplication by dok_id
-- Contains flattened document metadata, activities, proposals, references
-- Subtable entities (aktivitet, bilaga, forslag, intressent, motforslag, referens) are in separate stg models
--
-- Deduplication: When the same dok_id appears multiple times (e.g. from incremental loads),
-- we keep the row with the latest _dlt_load_id to get the most recent version.
--
-- Materialized as VIEW: Downstream dbt models only use metadata columns (not HTML),
-- so DuckDB's columnar format skips the ~10GB dokument__html column entirely.
-- For HTML content access, use int_document_content (pre-filtered, materialized table).

select
    dokument__hangar_id,
    dokument__dok_id,
    dokument__rm,
    -- Pre-computed riksmote_year for efficient filtering (avoids CAST(split_part(...)) in queries)
    -- Handles both '2022/23' and '2022-23' formats by replacing hyphen with slash before splitting
    -- NULLIF handles empty strings that can't be cast to integer
    TRY_CAST(split_part(replace(NULLIF(dokument__rm, ''), '-', '/'), '/', 1) AS INTEGER) as riksmote_year,
    dokument__beteckning,
    dokument__typ,
    dokument__subtyp,
    dokument__doktyp,
    dokument__typrubrik,
    dokument__dokumentnamn,
    dokument__debattnamn,
    dokument__tempbeteckning,
    dokument__organ,
    dokument__mottagare,
    dokument__nummer,
    dokument__slutnummer,
    dokument__datum,
    dokument__systemdatum,
    dokument__publicerad,
    dokument__titel,
    dokument__subtitel,
    dokument__status,
    dokument__htmlformat,
    dokument__relaterat_id,
    dokument__source,
    dokument__sourceid,
    dokument__dokument_url_text,
    dokument__dokument_url_html,
    dokument__dokumentstatus_url_xml,
    dokument__utskottsforslag_url_xml,
    dokument__html,
    _dokumentlista_id,
    _dlt_load_id,
    _dlt_id,
    dokument__publicerad__v_text,
    dokuppgift__uppgift__kod,
    dokuppgift__uppgift__namn,
    dokuppgift__uppgift__text,
    dokuppgift__uppgift__dok_id,
    dokuppgift__uppgift__systemdatum,
    dokmotforslag__motforslag__nummer,
    dokmotforslag__motforslag__rubrik,
    dokmotforslag__motforslag__partier,
    dokmotforslag__motforslag__typ,
    dokmotforslag__motforslag__utskottsforslag_punkt,
    dokutskottsforslag__utskottsforslag__punkt,
    dokutskottsforslag__utskottsforslag__rubrik,
    dokutskottsforslag__utskottsforslag__forslag,
    dokutskottsforslag__utskottsforslag__beslutstyp,
    dokutskottsforslag__utskottsforslag__motforslag_nummer,
    dokutskottsforslag__utskottsforslag__motforslag_partier,
    dokutskottsforslag__utskottsforslag__votering_id,
    dokutskottsforslag__utskottsforslag__votering_sammanfattning_html,
    dokutskottsforslag__utskottsforslag__votering_url_xml,
    dokutskottsforslag__utskottsforslag__rm,
    dokutskottsforslag__utskottsforslag__bet,
    dokutskottsforslag__utskottsforslag__vinnare,
    dokutskottsforslag__utskottsforslag__voteringskrav,
    dokutskottsforslag__utskottsforslag__beslutsregelkvot,
    dokutskottsforslag__utskottsforslag__beslutsregelparagraf,
    dokutskottsforslag__utskottsforslag__punkttyp,
    dokreferens__referens__referenstyp,
    dokreferens__referens__uppgift,
    dokreferens__referens__ref_dok_id,
    dokreferens__referens__ref_dok_typ,
    dokreferens__referens__ref_dok_rm,
    dokreferens__referens__ref_dok_bet,
    dokreferens__referens__ref_dok_titel,
    dokreferens__referens__ref_dok_subtitel,
    dokreferens__referens__ref_dok_subtyp,
    dokreferens__referens__ref_dok_dokumentnamn,
    dokforslag__forslag__nummer,
    dokforslag__forslag__beteckning,
    dokforslag__forslag__lydelse,
    dokforslag__forslag__lydelse2,
    dokforslag__forslag__utskottet,
    dokforslag__forslag__kammaren,
    dokforslag__forslag__behandlas_i,
    dokforslag__forslag__behandlas_i_punkt,
    dokforslag__forslag__kammarbeslutstyp,
    dokforslag__forslag__intressent,
    dokforslag__forslag__avsnitt,
    dokforslag__forslag__grundforfattning,
    dokforslag__forslag__andringsforfattning,
    dokument__text,
    dokument__avdelningar__avdelning,
    dokaktivitet__aktivitet__kod,
    dokaktivitet__aktivitet__namn,
    dokaktivitet__aktivitet__datum,
    dokaktivitet__aktivitet__status,
    dokaktivitet__aktivitet__ordning,
    dokaktivitet__aktivitet__process,
    dokintressent__intressent__intressent_id,
    dokintressent__intressent__namn,
    dokintressent__intressent__partibet,
    dokintressent__intressent__ordning,
    dokintressent__intressent__roll
from {{ source('raw_riksdagen', 'dokumentstatus') }}
where dokument__dok_id is not null
qualify row_number() over (partition by dokument__dok_id order by _dlt_load_id desc) = 1
